### ISSUE TITLE
Must this package depend on R>=3.2.2 ?

### ISSUE THREAD

**Issue by franticspider** [sgibb/MALDIquantForeign#18]
Hello,

I'm puzzled as to why MALDIquant can work with R>=3.2.0 but MALDIquantForeign depends on R>=3.2.2. If this is not necessary, please amend MALDIquantForeign to depend on R>=3.2.0

many thanks,

Simon

**Comment by sgibb** [comment]
MALDIquantForeign 0.10 uses the built-in https support of R >= 3.2.2. In earlier versions MALDIquantForeign depends on the downloader package for this.
Is R >= 3.2.2 a problem for you?
