### ISSUE TITLE
unitAccession not followed by unitName

### ISSUE THREAD

**Issue by JHKobarg** [sgibb/MALDIquantForeign#22]
Hi, in this cvParam only the unitAccession is given, but the unitName is not given; please consider adding `unitName="number of counts"` to the function in line 329 to make it valid mzML

https://github.com/sgibb/MALDIquantForeign/blob/4c6b47f8690886c908562eab97849240cbee7412/R/mzMl-functions.R#L326-L329

**Comment by frulo** [comment]
see https://github.com/sgibb/MALDIquantForeign/pull/23
