### ISSUE TITLE
Error when reading Analyze7.5 files

### ISSUE THREAD

**Issue by foellmelanie** [sgibb/MALDIquantForeign#27]
Hi, 
I am wondering if this check can be relaxed or changed into a warning:
`  if (size != 348 && size != 384) {
    stop(sQuote(filename), " is no ANALYZE header file.")
}`
I have some Analyze7.5 files that do not match this size requirement but work for example in Cardinal. 
Thanks,
Melanie

**Comment by sgibb** [comment]
Of course that wouldn't be a problem. But what is would happen in the next lines? E.g. how to find out the endianess of the file?
```r
  f <- file(filename, open="rb")
  on.exit(close(f))

  ## first 4 bytes have to be 348 in little endian mode
  ## (384 for ABSciex)
  endian <- ifelse(readBin(f, "integer", n=1, size=4, endian="little") %in%
                   c(348, 384), "little", "big")
```

Could you send me the output of and/or attach the header file here?
```r
  f <- file(filename, open="rb")
  endian <- readBin(f, "integer", n=1, size=4, endian="little")
  print(endian)
  close(f)
```

**Comment by sgibb** [comment]
I close this issue because it is nearly 3 years old. Please feel free to reopen it if it is still relevant and you could provide some header details.
