### ISSUE TITLE
Error when skipping lines in text file

### ISSUE THREAD

**Issue by SamGG** [sgibb/MALDIquantForeign#29]
Hi,
Thanks for this package.
I guess that the beginning of the code L24-L35 is guessing the right parameters for read.table. But then read.table L38 is not applied to the raw file but to already processed text lines. Because skipping lines already took place, it should not be applied twice. I think that the file name actually should be given to read.table L38 instead of the text variable.
Best.
https://github.com/sgibb/MALDIquantForeign/blob/37fbb16c20ceee8724a4cc1e4c40a17dd74444b4/R/importTab-functions.R#L24-L39

**Comment by sgibb** [comment]
Dear @SamGG thanks for the bug report! You are right the `skip` is done twice.
> I think that the file name actually should be given to read.table L38 instead of the text variable.

In that case the file would be read twice (`readLines` and `read.table`) which would be unnecessary. I will just ignore the `skip` argument in `read.table`.

**Comment by SamGG** [comment]
Thanks for considering my report.
Best.
