### ISSUE TITLE
Reading/Converting Bruker's MALDI-FTICR .d file

### ISSUE THREAD

**Issue by YonghuiDong** [sgibb/MALDIquantForeign#31]
Hi Sebastian,

I would like to use MALDIQuant to analyse Bruker's MALDI-FTICR data.  But I don't know how do I convert the raw file  to mzML file or other MALDIquantForeign supported format. Or will MALDIquantForeign support such data type?

Here I upload a compressed sample data. The acquired data is basically a folder, which contains various files in it.  It can be opened with Bruker's DataAnalysis software, and can be exported to, for instance, .xml  or .ascii file. But the software does not support exporting to mzML format.

Here I attached one example data, could you please help?
[WT.d.zip](https://github.com/sgibb/MALDIquantForeign/files/5128668/WT.d.zip)

Thanks a lot.

Dong

**Comment by sgibb** [comment]
I never used FTICR data. Isn't the ascii file a 2 column text file that could be imported?

**Comment by YonghuiDong** [comment]
@sgibb I have tried with the .ascii file. I have waited for more than 1 hour and the importing process still didn't finish. 

Dong

**Comment by sgibb** [comment]
Could you attach an example .ascii file?

12.09.2020 20:55:59 Dong <notifications@github.com>:

**Comment by YonghuiDong** [comment]
Hi Sebastian,

Sorry for my late reply. I have checked the converted .ascii file. It is a one row file, not a two-column (mz-intensity) file. That's why I failed to read it with MALDIquantForeign.

The Bucker software DataAnalysis allows to convert raw .d file to a xy format file, which is a two-column (mz-intensity) text file.

Here I send you one example of the converted file.

[test_xy_format.zip](https://github.com/sgibb/MALDIquantForeign/files/5238870/test_xy_format.zip)

Thanks a lot for your help.

Dong

**Comment by sgibb** [comment]
You could import this file by using the `importTab` function and specify the `pattern` (file name pattern/extension) and `sep` (field separator) arguments:
```r
library("MALDIquantForeign")
s <- importTab("test.xy", pattern = "\\.xy", header = FALSE, sep = " ")
plot(s[[1]])
```
![Rplot001](https://user-images.githubusercontent.com/1828443/93577231-14f47180-f99c-11ea-8cbd-502852d8035a.png)
