### ISSUE TITLE
Unable to write imzML files via exportImzMl

### ISSUE THREAD

**Issue by denis-abusammour** [sgibb/MALDIquantForeign#33]
`exportImzMl` complains when attempting writing to an imzML file, here is a reproducible example (file attached 
[massPeaksList.gz](https://github.com/sgibb/MALDIquantForeign/files/7594199/massPeaksList.gz) ):  

```
s <- readRDS(file = "massPeaksList.gz")
MALDIquantForeign::exportImzMl(x = s, path = "test.imzML", processed = TRUE)

Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'coordinates<-' of mode 'function' was not found
  
packageVersion("MALDIquantForeign")
[1] ‘0.12’
```

The issue is resolved when explicitly loading `MALDIquant` into the environment. The issue appears to be in `.writeImzMlDocument` function in `imzMl-functions.R` line #48 `coordinates(x) <- coordinates`, the function `coordinates` is called without specifying `MALDIquant` package namespace. 

Also the documentation of `?MALDIquantForeign::exportImzMl` says the the input should be "a `MassSpectrum` object or a list of `MassSpectrum` objects" but it didn't have any issues exporting a list of `MassPeaks` objects (the attached file).

**Comment by sgibb** [comment]
Thanks for you report and the example data. Unfortunately I can't reproduce your problem in a clean R session. `MALDIquant` is in the `Depends` of `MALDIquantForeign` and also imported via `NAMESPACE`. So it should not be necessary to call `MALDIquant::coordinates` implicitly. Do you have another package/code loaded that overwrites `coordinates` (function/variable name)?

> Also the documentation of `?MALDIquantForeign::exportImzMl` says the the input should be "a `MassSpectrum` object or a list of `MassSpectrum` objects" but it didn't have any issues exporting a list of `MassPeaks` objects (the attached file).

Indeed. It is never checked. I assume it is a feature?! I will change the documentation accordingly.

**Comment by denis-abusammour** [comment]
Thanks for your reply. 

> Do you have another package/code loaded that overwrites coordinates (function/variable name)?

I think not. I strictly use `::` operator when calling functions of packages. But it could be a bug in another package that imports `sp` package which does have a `coordinates` function. I will check that. 

> MALDIquant is in the Depends of MALDIquantForeign and also imported via NAMESPACE. So it should not be necessary to call MALDIquant::coordinates implicitly.

Yet, on line #22 of `imzml-functions.R`, `MALDIquant::coordinates` is used. Is this for a reason? wouldn't it be safer to call `MALDIquant` functions via their namespace to protect against accidental overwriting by other packages? 

> Indeed. It is never checked. I assume it is a feature?! I will change the documentation accordingly.

Yes please, there is no reason for having `exportImzML` only accepting `MassSpectrum` objects since one could set the imzML type in its `processed` argument.

**Comment by sgibb** [comment]
Using `::` everywhere will decrease runtime performance cause `::` is itself a function that takes it time for method dispatching. But using it in the export functions wouldn't affect the performance.

> Yet, on [line 22 of `imzml-functions.R`](https://github.com/sgibb/MALDIquantForeign/blob/73f3a9583172fd46d027b2e6936fd13661cb6cd0/R/imzMl-functions.R#L22), `MALDIquant::coordinates` is used. Is this for a reason?

To be honest I don't know why I explicitly used `MALDIquant::coordinates` here.
